[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
dependencies = ["maturin", "patchelf"]
name = "pyadb_client"
dynamic = ["version"] # Let the build system automatically set package version
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
