name: Rust - Quality

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: "clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --all-features

  fmt:
    name: "fmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run formatter
        run: cargo fmt --all --check

  doc:
    name: "doc"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run doc
        run: cargo doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: "-D warnings"

  tests:
    name: "tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose --all-features
